kind: Pod
apiVersion: v1
metadata:
  name: kubelet-density-{{.Iteration}}
  labels:
    name: kubelet-density
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  containers:
  - name: kubelet-density
    image: {{.containerImage}}
    imagePullPolicy: IfNotPresent
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - "ALL"
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
