---
global:
  gc: false
jobs:
  - name: kubelet-density
    jobIterations: 25
    preLoadImages: true
    namespacedIterations: false
    namespace: kubelet-density
    waitWhenFinished: true
    podWait: false
    objects:
      - objectTemplate: templates/pod.yml
        replicas: 1
        inputVars:
          containerImage: registry.k8s.io/pause:3.10
